# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Telescope']

# Cell
class Telescope:
    '''
    Main API class
    '''
    def __init__(self):
        pass