# AUTOGENERATED! DO NOT EDIT! File to edit: ../30_process.ipynb.

# %% auto 0
__all__ = []

# %% ../30_process.ipynb 3
import configparser
from os.path import expanduser
from astroquery.astrometry_net import AstrometryNet
