# AUTOGENERATED! DO NOT EDIT! File to edit: ../20_util.ipynb.

# %% ../20_util.ipynb 2
from __future__ import annotations

# %% auto 0
__all__ = []

# %% ../20_util.ipynb 3
def cleanup(s: str) -> str:
    '''
    Remove non-asci characters from the string.
    '''
    return s.encode('ascii','ignore').decode('ascii','ignore')
