# AUTOGENERATED! DO NOT EDIT! File to edit: ../40_vsapp.ipynb.

# %% auto 0
__all__ = []

# %% ../40_vsapp.ipynb 2
import configparser
from fastcore.basics import patch
from os.path import expanduser
from ouscope.core import Telescope
from ouscope.solver import Solver
from matplotlib import pyplot as plt
from collections import namedtuple
from sqlitedict import SqliteDict

# %% ../40_vsapp.ipynb 3
plt.rcParams['image.cmap'] = 'gray'

# %% ../40_vsapp.ipynb 10
def make_color_image(layers, black=1.0, Q=5, stretch=200, mults=(0.95, 1.0, 1.0), order='BVR'):

    seq = argsort(list(order))
    b, r, g = (m*layers[l] for m,l in zip(mults,seq))
    # print([order[i] for i in seq])
    
    try :
        r_r, r_f = aa.register(r, g, detection_sigma=10)
    except TypeError:
        r_r = r
        
    try :
        b_r, b_f = aa.register(b, g, detection_sigma=10)
    except TypeError:
        b_r = b
        
    minlev = np.array([sigma_clipped_stats(l, sigma=3.0)[1] for l in (r,g,b)])
    return make_lupton_rgb(0.9*r_r, g, b_r, minimum=black*minlev, Q=Q, stretch=stretch)
